import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import TopNav from "@/components/TopNav";
import BottomNav from "@/components/BottomNav";
import Hero from "@/sections/Hero";
import About from "@/sections/About";
import Projects from "@/sections/Projects";
import Contact from "@/sections/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/whitelogo.png" />
      </Head>
      <main>
        <TopNav />
        <BottomNav />
        <Hero />
        <About />
        <Projects />
        <Contact />
      </main>
    </>
  );
}
